# This file is the entry point to configure security settings for the production environment
# https://symfony.com/doc/current/security.html

# This file is intentionally commented out to avoid conflicts with the base security.yaml
# Uncomment and adjust when you need to override specific settings for production

#security:
#    password_hashers:
#        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
#
#    providers:
#        app_user_provider:
#            entity:
#                class: App\Entity\User
#                property: email
#
#    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            lazy: true
#            provider: app_user_provider
#            custom_authenticator: App\Security\LoginFormAuthenticator
#            
#            # Activate remember me feature with a timeout of 1 week (604800 seconds)
#            remember_me:
#                secret: '%kernel.secret%'
#                lifetime: 604800
#                path: /
#                
#            logout:
#                path: app_logout
#                # Target route after logout
#                target: app_home
#
#    # Prevent access to specific routes without required role
#    access_control:
#        # You can add production-specific access controls here
#        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/profile, roles: ROLE_USER }
#        - { path: ^/book/new, roles: ROLE_USER }
#        - { path: ^/book/\d+/edit, roles: ROLE_USER }
#        - { path: ^/category/new, roles: ROLE_ADMIN }
#        - { path: ^/category/\d+/edit, roles: ROLE_ADMIN }
#        - { path: ^/author/new, roles: ROLE_USER }
#        - { path: ^/author/\d+/edit, roles: ROLE_USER }
#        - { path: ^/ai/stats/report, roles: ROLE_ADMIN }
#        
#    # Force HTTPS in production
#    access_decision_manager:
#        strategy: unanimous
        
when@dev:
    security:
        # Allow development tools in dev environment
        firewalls:
            dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false
