<?php

namespace ContainerWTOeiHU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Oi6VS8jService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Oi6VS8j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Oi6VS8j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'author' => ['privates', '.errored..service_locator.Oi6VS8j.App\\Entity\\Author', NULL, 'Cannot autowire service ".service_locator.Oi6VS8j": it needs an instance of "App\\Entity\\Author" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'author' => 'App\\Entity\\Author',
            'entityManager' => '?',
        ]);
    }
}
