<?php

namespace ContainerWTOeiHU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AuthorRepository' shared autowired service.
     *
     * @return \App\Repository\AuthorRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AuthorRepository'] = new \App\Repository\AuthorRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
