<?php

namespace ContainerWTOeiHU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorControllerindexService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator..WkD5qS.App\Controller\AuthorController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..WkD5qS.App\\Controller\\AuthorController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'authorRepository' => ['privates', 'App\\Repository\\AuthorRepository', 'getAuthorRepositoryService', true],
        ], [
            'authorRepository' => 'App\\Repository\\AuthorRepository',
        ]))->withContext('App\\Controller\\AuthorController::index()', $container);
    }
}
