<?php

namespace ContainerWTOeiHU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorControllerdeleteService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Oi6VS8j.App\Controller\AuthorController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Oi6VS8j.App\\Controller\\AuthorController::delete()'] = ($container->privates['.service_locator.Oi6VS8j'] ?? $container->load('get_ServiceLocator_Oi6VS8jService'))->withContext('App\\Controller\\AuthorController::delete()', $container);
    }
}
