<?php

namespace ContainerWTOeiHU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthor2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.s29OJQA.App\Entity\Author' shared service.
     *
     * @return \App\Entity\Author
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.s29OJQA": it needs an instance of "App\\Entity\\Author" but this type has been excluded in "config/services.yaml".');
    }
}
