<?php

namespace ContainerWTOeiHU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AuthorController::index' => ['privates', '.service_locator..WkD5qS.App\\Controller\\AuthorController::index()', 'getAuthorControllerindexService', true],
            'App\\Controller\\AuthorController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\AuthorController::new()', 'getAuthorControllernewService', true],
            'App\\Controller\\AuthorController::show' => ['privates', '.service_locator.s29OJQA.App\\Controller\\AuthorController::show()', 'getAuthorControllershowService', true],
            'App\\Controller\\AuthorController::edit' => ['privates', '.service_locator.Oi6VS8j.App\\Controller\\AuthorController::edit()', 'getAuthorControllereditService', true],
            'App\\Controller\\AuthorController::delete' => ['privates', '.service_locator.Oi6VS8j.App\\Controller\\AuthorController::delete()', 'getAuthorControllerdeleteService', true],
            'App\\Controller\\BookController::index' => ['privates', '.service_locator.ErcxNfJ.App\\Controller\\BookController::index()', 'getBookControllerindexService', true],
            'App\\Controller\\BookController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\BookController::new()', 'getBookControllernewService', true],
            'App\\Controller\\BookController::show' => ['privates', '.service_locator.b3R8WOF.App\\Controller\\BookController::show()', 'getBookControllershowService', true],
            'App\\Controller\\BookController::edit' => ['privates', '.service_locator.52LSSp5.App\\Controller\\BookController::edit()', 'getBookControllereditService', true],
            'App\\Controller\\BookController::delete' => ['privates', '.service_locator.52LSSp5.App\\Controller\\BookController::delete()', 'getBookControllerdeleteService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.MTCWnA5.App\\Controller\\CategoryController::index()', 'getCategoryControllerindexService', true],
            'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\CategoryController::new()', 'getCategoryControllernewService', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.ZAUGEyP.App\\Controller\\CategoryController::show()', 'getCategoryControllershowService', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.gADJ5td.App\\Controller\\CategoryController::edit()', 'getCategoryControllereditService', true],
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.gADJ5td.App\\Controller\\CategoryController::delete()', 'getCategoryControllerdeleteService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.ErcxNfJ.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\ProfileController::index' => ['privates', '.service_locator.egipcEH.App\\Controller\\ProfileController::index()', 'getProfileControllerindexService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.8AJzrpw.App\\Controller\\SecurityController::register()', 'getSecurityControllerregisterService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AuthorController:index' => ['privates', '.service_locator..WkD5qS.App\\Controller\\AuthorController::index()', 'getAuthorControllerindexService', true],
            'App\\Controller\\AuthorController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\AuthorController::new()', 'getAuthorControllernewService', true],
            'App\\Controller\\AuthorController:show' => ['privates', '.service_locator.s29OJQA.App\\Controller\\AuthorController::show()', 'getAuthorControllershowService', true],
            'App\\Controller\\AuthorController:edit' => ['privates', '.service_locator.Oi6VS8j.App\\Controller\\AuthorController::edit()', 'getAuthorControllereditService', true],
            'App\\Controller\\AuthorController:delete' => ['privates', '.service_locator.Oi6VS8j.App\\Controller\\AuthorController::delete()', 'getAuthorControllerdeleteService', true],
            'App\\Controller\\BookController:index' => ['privates', '.service_locator.ErcxNfJ.App\\Controller\\BookController::index()', 'getBookControllerindexService', true],
            'App\\Controller\\BookController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\BookController::new()', 'getBookControllernewService', true],
            'App\\Controller\\BookController:show' => ['privates', '.service_locator.b3R8WOF.App\\Controller\\BookController::show()', 'getBookControllershowService', true],
            'App\\Controller\\BookController:edit' => ['privates', '.service_locator.52LSSp5.App\\Controller\\BookController::edit()', 'getBookControllereditService', true],
            'App\\Controller\\BookController:delete' => ['privates', '.service_locator.52LSSp5.App\\Controller\\BookController::delete()', 'getBookControllerdeleteService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.MTCWnA5.App\\Controller\\CategoryController::index()', 'getCategoryControllerindexService', true],
            'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\CategoryController::new()', 'getCategoryControllernewService', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.ZAUGEyP.App\\Controller\\CategoryController::show()', 'getCategoryControllershowService', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.gADJ5td.App\\Controller\\CategoryController::edit()', 'getCategoryControllereditService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.gADJ5td.App\\Controller\\CategoryController::delete()', 'getCategoryControllerdeleteService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.ErcxNfJ.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\ProfileController:index' => ['privates', '.service_locator.egipcEH.App\\Controller\\ProfileController::index()', 'getProfileControllerindexService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.8AJzrpw.App\\Controller\\SecurityController::register()', 'getSecurityControllerregisterService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AuthorController::index' => '?',
            'App\\Controller\\AuthorController::new' => '?',
            'App\\Controller\\AuthorController::show' => '?',
            'App\\Controller\\AuthorController::edit' => '?',
            'App\\Controller\\AuthorController::delete' => '?',
            'App\\Controller\\BookController::index' => '?',
            'App\\Controller\\BookController::new' => '?',
            'App\\Controller\\BookController::show' => '?',
            'App\\Controller\\BookController::edit' => '?',
            'App\\Controller\\BookController::delete' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::new' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\ProfileController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AuthorController:index' => '?',
            'App\\Controller\\AuthorController:new' => '?',
            'App\\Controller\\AuthorController:show' => '?',
            'App\\Controller\\AuthorController:edit' => '?',
            'App\\Controller\\AuthorController:delete' => '?',
            'App\\Controller\\BookController:index' => '?',
            'App\\Controller\\BookController:new' => '?',
            'App\\Controller\\BookController:show' => '?',
            'App\\Controller\\BookController:edit' => '?',
            'App\\Controller\\BookController:delete' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:new' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\ProfileController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:register' => '?',
        ]));
    }
}
