<?php

namespace ContainerWTOeiHU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AuthorType' shared autowired service.
     *
     * @return \App\Form\AuthorType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AuthorType'] = new \App\Form\AuthorType();
    }
}
