<?php

namespace ContainerWTOeiHU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorControllershowService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.s29OJQA.App\Controller\AuthorController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s29OJQA.App\\Controller\\AuthorController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'author' => ['privates', '.errored..service_locator.s29OJQA.App\\Entity\\Author', NULL, 'Cannot autowire service ".service_locator.s29OJQA": it needs an instance of "App\\Entity\\Author" but this type has been excluded in "config/services.yaml".'],
        ], [
            'author' => 'App\\Entity\\Author',
        ]))->withContext('App\\Controller\\AuthorController::show()', $container);
    }
}
