<?php

namespace ContainerWTOeiHU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookControllerindexService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ErcxNfJ.App\Controller\BookController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ErcxNfJ.App\\Controller\\BookController::index()'] = ($container->privates['.service_locator.ErcxNfJ'] ?? $container->load('get_ServiceLocator_ErcxNfJService'))->withContext('App\\Controller\\BookController::index()', $container);
    }
}
