<?php

namespace ContainerWTOeiHU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateAdminCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\CreateAdminCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\CreateAdminCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-admin', [], 'Creates an admin user', false, #[\Closure(name: 'App\\Command\\CreateAdminCommand')] fn (): \App\Command\CreateAdminCommand => ($container->privates['App\\Command\\CreateAdminCommand'] ?? $container->load('getCreateAdminCommandService')));
    }
}
