<?php

namespace ContainerWTOeiHU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_Handler_DeprecationFilterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'monolog.handler.deprecation_filter' shared service.
     *
     * @return \Monolog\Handler\FilterHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['monolog.handler.deprecation_filter'] = new \Monolog\Handler\FilterHandler(($container->privates['monolog.handler.deprecation'] ?? $container->load('getMonolog_Handler_DeprecationService')), 'DEBUG', 'info', true);
    }
}
