<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWTOeiHU\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWTOeiHU/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerWTOeiHU.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerWTOeiHU\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerWTOeiHU\App_KernelProdContainer([
    'container.build_hash' => 'WTOeiHU',
    'container.build_id' => '043548cf',
    'container.build_time' => 1747440973,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWTOeiHU');
